AstarNetwork/astarwebsite_v2

components/Header.vue
components/MobileNav.vue

Add Japan link in header and mobile header.

Add Japan Link

---

components/developers/Hero.vue

Misspelling to change "**mulichain**" to "**multichain**"

Main Description Developer Page

---

.github/workflows/firebase-hosting-merge.yml
.github/workflows/firebase-hosting-pull-request.yml

Checking index.html generated before deploying to firebase

Check if index.html generated or not

---

components/Button.vue
components/japan/Newsletter.vue
components/japan/Register.vue
pages/japan.vue

- Add register buttons for the organization
- Add newsletter section to the bottom

Add register buttons in Astar Japan Lab page

---

components/starmap/Contents.vue

Please check the [preview](https://astar-home--pr34-feature-downscale-st-9pceiory.web.app/starmap/) with a wide screen. Thank you

Downscale starmap

---

components/japan/Register.vue

we detect bag on the old URL, so I changed it.

Change the Applicant URL

---

pages/index.vue

Add the hiring link

---

components/community/Hero.vue
components/community/Links.vue
components/developers/Hero.vue
pages/community.vue
pages/developers.vue

Fix sub-page hero layout for small screen

---

pages/contact.vue

align buttons on the contact page

---

components/Footer.vue
components/community/Links.vue
components/community/Wayfinding.vue
components/developers/Hero.vue
components/incubation/Footer.vue
pages/contact.vue

1. [Footer](https://astar-home--pr89-update-discord-link-ritj30a9.web.app/)
2. [Developer page](https://astar-home--pr89-update-discord-link-ritj30a9.web.app/developers)
3. [Community page](https://astar-home--pr89-update-discord-link-ritj30a9.web.app/community)
4. [Contact page](https://astar-home--pr89-update-discord-link-ritj30a9.web.app/contact)
5. [Sony incubation program page footer](https://astar-home--pr89-update-discord-link-ritj30a9.web.app/incubation/)

Update discord link

---

components/home/Hero.vue
components/home/Welcome.vue
layouts/default.vue

Update astar brand

---

components/Header.vue
components/developers/Toolkit.vue
components/home/Backers.vue
components/japan/Members.vue
components/japan/News.vue
nuxt.config.ts
pages/community/ecosystem.vue

Works and bring online both graphs

adding a second graphql client

---

.github/workflows/broken-links-action.yml
.lycheeignore

This PR adds a github action which check for broken links in the repo. It will check all repository links once per day and create an issue in case of errors.
**Check list**
**Release notes:**
- broken links check
**This pull request makes the following changes:**
**Adds**
- broken links check

Broken Link action

---

README.md
components/Footer.vue
pages/community/ecosystem.vue
pages/index.vue

Fix broken links

---

.lycheeignore

Add ignore urls #122

---

.lycheeignore

update ignore urls

---

components/home/Newsletter.vue
pages/blog/[slug].vue
pages/blog/index.vue
pages/blog/tag/[tag].vue
pages/index.vue

Added a newsletter section to:
- [main page](https://astar-home--pr124-newsletter-frw1cwv1.web.app/), below the Recommended Reading section
- [blog index page](https://astar-home--pr124-newsletter-frw1cwv1.web.app/blog)
- [blog article page](https://astar-home--pr124-newsletter-frw1cwv1.web.app/blog/using-nf-ts-for-enterprise-marketing-38454), below the author's profile section
- [blog tag page](https://astar-home--pr124-newsletter-frw1cwv1.web.app/blog/tag/NFTs)

Add newsletter

---

app.vue
public/js/astarAi.js

Astari on HP

---

app.vue
components/ContactButton.vue
components/Gdpr.vue
layouts/default.vue
layouts/incubation.vue

Add sticky button to contact page

---

yarn.lock

Reverts AstarNetwork/astarwebsite_v2#243

Revert "Bump vite from 4.3.4 to 4.3.9"

---

components/japan/Blog.vue
components/japan/Members.vue
components/japan/UseCases.vue
lang/en-japan.json
lang/ja-japan.json
lang/ja.json

Preview URL: https://astar-home--pr334-astar-japan-lab-japa-u5teb0gk.web.app/ja/japan
https://docs.google.com/document/d/1bNrkQt6OtBKb9hl-k0f3O2EMzwWB2LTmA1pq79ybkW4/edit?usp=sharing

Update Astar Japan Lab Japanese page

---

components/ecosystem/LogoList.vue

Adds search bar that filters the projects name
searching:

feat: add search bar

---

components/home/Features.vue

hide yoki button

---

components/home/Features.vue

Reverts AstarNetwork/astarwebsite_v2#345

Revert "hide yoki button"

---

components/home/Funding.vue
lang/en-contact.json
lang/ja-contact.json
lang/ko-contact.json
pages/contact.vue

replace to the financial support form

---

pages/brand-asset-kit.vue

- Fixed the brand asset kit page title

fix: Brand asset kit page title

---

assets/css/tailwind.css
components/blog/TableOfContents.vue
components/blog/TableOfContentsItem.vue
pages/blog/[slug].vue

- ToC will be displayed when the post has more than 2 titles
- Only display the first level titles

Add blog ToC styling

---

components/blog/index.ts
pages/blog/[slug].vue
pages/blog/tag/[tag].vue

Fixes https://github.com/AstarNetwork/astarwebsite_v2/issues/351
- Handle tags with spaces
- Empty tags redirect to /blog/
- Non numeric id from slug redirect to /blog/
- Page not longer load the tag section if no tags are used

fix: tags with space, handle no tags

---

components/Header.vue
components/LangSwitcher.vue

- Added the "Astar Portal" button to the header
**Check list**

add astar portal button to the header

---

data/links.ts

> Update Career URL as new Startale career page
**Check list**
**This pull request makes the following changes:**
**Changes**
- update career url as startale career page

update career url as startale career page

---

lang/en-home.json
lang/en.json
lang/ja-home.json
lang/ja.json

- Added the space between “Connecting” and “you” of the main copy on the homepage
- Fixed the tagline text
**Check list**
**This pull request makes the following changes:**
**Adds**
- (ex: Add feature A)
**Fixes**
- (ex: Fix validation function)
**Changes**
- (ex: Change document B)
**To-dos**
> \*Feel free to remove this section if it's not applicable

Fix main copy space

---

components/community/Ambassador.vue
components/community/OnlineCommunity.vue
data/links.ts

> The Ambassador link was broken, updated and replace hard-coded link
**Check list**
**This pull request makes the following changes:**
**Fixes**
- Ambassador link

Fix ambassador link
